---
- name: Installs NCPA Agent 
  become: yes
  become_method: sudo
  user: centos
  hosts: all
  tasks: 
  - name: Creates a repo
    when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7")
    shell: "rpm -Uvh http://repo.nagios.com/nagios/7/nagios-repo-7-4.el7.noarch.rpm"
    ignore_errors: true
  - name: Install NCPA
    when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7")
    package: 
      name: ncpa 
      state: latest
  - name: Change a line
    lineinfile:
      path: /usr/local/ncpa/etc/ncpa.cfg
      regexp: '^community_string'
      line: 'community_string = Str0ngT0k3n1'
    notify: RESTART_NCPA
  handlers: 
    - name: RESTART_NCPA
      systemd:
        name: ncpa_listener
        state: restarted