---
- name: Installs packages
  become: yes
  become_method: sudo
  user: centos
  hosts: all
  tasks: 
  - name: Install wordpress
    get_url:
      url:

    unarchive: 
    
    loop to install packages:
    httpd
    telnet
    mysql